### ISSUE TITLE
OAUTH documentation

### ISSUE THREAD

**Issue by giardiaspace** [alpinemail/alpine#1]
I am trying to find the information that was previously available here:
http://alpine.x10host.com/alpine/alpine-info/misc/AuthorizeAlpineGmail.html

The site seems to be taken down.

**Comment by allenluce** [comment]
You should now be able to find this at Eduardo Chappa's authoritative Alpine site: https://alpineapp.email/alpine/alpine-info/misc/AuthorizeAlpineGmail.html
